apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cosine-similarity-build
  namespace: osvaldorioz-1-dev
spec:
  output:
    to:
      kind: ImageStreamTag
      name: cosine-similarity:latest
  source:
    git:
      uri: https://github.com/osvaldorioz/py-cosine-sim-ocp4.git
      ref: main
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: python:3.12-ubi9
      env:
      - name: PIP_NO_CACHE_DIR
        value: "true"
      - name: HF_HOME
        value: "/opt/app-root/src/cache"
      - name: APP_MODULE  # Añadido para especificar el módulo de la aplicación
        value: "main:app"
  triggers:
  - type: ConfigChange
  - type: ImageChange