apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosine-similarity-deployment
  namespace: osvaldorioz-1-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosine-similarity
  template:
    metadata:
      labels:
        app: cosine-similarity
    spec:
      containers:
      - name: cosine-similarity
        image: image-registry.openshift-image-registry.svc:5000/osvaldorioz-1-dev/cosine-similarity@sha256:e30af60c4dbe8a9008abebc2367e4a60c575c5ef249d76223f14a153f0df0198
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: HF_HOME
          value: "/app/cache"